Repository LikeLion-CAU-9th/DoMain, pull requests merged in 2021-08, with the labels that each got.

#23 [BE] - Refactor: resolve path confilct
  src/DoMain/mainpage/urls.py
  src/DoMain/store/templates/AssetStoreMainPage.html
  src/DoMain/store/views.py
Labels: fix

#24 [FE] - Feat: base template
  src/DoMain/DoMain/settings.py
  src/DoMain/DoMain/templates/base.html
  src/DoMain/store/static/css/commons/navbar.css
  src/DoMain/store/static/css/test.sass
  src/DoMain/store/templates/subpage.html
Labels: feat

#28 [FE] - Feat: Asset store main page carousel edited
  src/DoMain/store/static/css/Mainpage.css
  src/DoMain/store/static/css/carousel.css
  src/DoMain/store/static/css/owl.carousel.css
  src/DoMain/store/static/css/owl.theme.default.css
  src/DoMain/store/static/image/custompage-1.jpg
  src/DoMain/store/static/image/custompage-2.png
  src/DoMain/store/static/image/custompage-3.png
  src/DoMain/store/static/image/custompage-4.png
  src/DoMain/store/static/js/bootstrap.js
  src/DoMain/store/static/js/carousel.js
  src/DoMain/store/static/js/jquery-3.6.0.js
  src/DoMain/store/static/js/owl.carousel.min.js
  src/DoMain/store/templates/AssetStoreMainPage.html
Labels: feat

#37 [widget] - searching widget
  src/DoMain/store/static/css/Mainpage.css
  src/DoMain/store/static/css/carousel.css
  src/DoMain/store/static/css/owl.carousel.css
  src/DoMain/store/static/css/owl.theme.default.css
  src/DoMain/store/static/image/custompage-1.jpg
  src/DoMain/store/static/image/custompage-2.png
  src/DoMain/store/static/image/custompage-3.png
  src/DoMain/store/static/image/custompage-4.png
  src/DoMain/store/static/js/bootstrap.js
  src/DoMain/store/static/js/carousel.js
  src/DoMain/store/static/js/jquery-3.6.0.js
  src/DoMain/store/static/js/owl.carousel.min.js
  src/DoMain/store/templates/AssetStoreMainPage.html
  src/DoMain/widget/models.py
  src/DoMain/widget/static/image/magnifying-glass.png
  src/DoMain/widget/static/searching/searching.js
  src/DoMain/widget/static/utils/widget.js
  src/DoMain/widget/templates/searching.html
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#38 [FE] - Feat: page connect in Store
  src/DoMain/DoMain/templates/base.html
  src/DoMain/store/static/js/cardDetailModal.js
  src/DoMain/store/templates/AssetStoreMainPage.html
  src/DoMain/store/templates/subpage.html
Labels: feat

#41 [widget] - merge to main
  src/DoMain/account/views.py
  src/DoMain/widget/models.py
  src/DoMain/widget/static/dday/dday.js
  src/DoMain/widget/static/image/magnifying-glass.png
  src/DoMain/widget/static/searching/searching.js
  src/DoMain/widget/static/utils/widget.js
  src/DoMain/widget/templates/dday.html
  src/DoMain/widget/templates/searching.html
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#33 [BE] - Feat: DB setting in Store
  src/DoMain/DoMain/settings.py
  src/DoMain/DoMain/templates/base.html
  src/DoMain/account/static/css/base.css
  src/DoMain/account/static/css/login.css
  src/DoMain/account/static/image/cir.svg
  src/DoMain/account/static/image/mail.svg
  src/DoMain/account/static/image/pass.svg
  src/DoMain/account/static/image/tri.svg
  src/DoMain/account/static/image/user.svg
  src/DoMain/account/static/js/login.js
  src/DoMain/account/templates/login.html
  src/DoMain/store/models.py
  src/DoMain/store/static/css/commons/navbar.css
  src/DoMain/store/static/css/owl.carousel.css
  src/DoMain/store/static/css/test.sass
  src/DoMain/store/templates/AssetStoreMainPage.html
  src/DoMain/store/templates/subpage.html
Labels: feat

#46 [widget] - Sticky note
  src/DoMain/widget/static/css/note.css
  src/DoMain/widget/static/stickynote/stickynote.js
  src/DoMain/widget/static/utils/widget.js
  src/DoMain/widget/templates/stickynote.html
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#45 [BE] add widget layout create/delete/clone functions and connects urls
  src/DoMain/account/views.py
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#47 [sub02] - Merge to main
  src/DoMain/account/views.py
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#48 [widget] - merge to main
  src/DoMain/widget/static/css/note.css
  src/DoMain/widget/static/dday/dday.js
  src/DoMain/widget/static/stickynote/stickynote.js
  src/DoMain/widget/static/utils/widget.js
  src/DoMain/widget/templates/dday.html
  src/DoMain/widget/templates/stickynote.html
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#43 [BE]- Feat: StoreWidget model class
  src/DoMain/store/migrations/0001_initial.py
  src/DoMain/store/migrations/__init__.py
  src/DoMain/store/models.py
Labels: feat

#50 [Merge] : Store app
  src/DoMain/store/migrations/0001_initial.py
  src/DoMain/store/migrations/__init__.py
  src/DoMain/store/models.py
Labels: feat

#49 [Layout] - add layout delete/create/clone and test files
  src/DoMain/mainpage/templates/test.html
  src/DoMain/mainpage/urls.py
  src/DoMain/mainpage/views.py
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#51 Feat main rendering
  src/DoMain/DoMain/settings.py
  src/DoMain/DoMain/urls.py
  src/DoMain/account/views.py
  src/DoMain/board/__init__.py
  src/DoMain/board/admin.py
  src/DoMain/board/apps.py
  src/DoMain/board/models.py
  src/DoMain/board/static/css/customPage.css
  src/DoMain/board/static/css/widget-static-style.css
  src/DoMain/board/static/image/magnifying-glass.png
  src/DoMain/board/static/img/App 21.png
  src/DoMain/board/static/img/App 22.png
  src/DoMain/board/static/img/App 24.png
  src/DoMain/board/static/js/customPage.js
  src/DoMain/board/static/js/layout-server.js
  src/DoMain/board/static/js/modal.js
  src/DoMain/board/static/js/widgetClick.js
  src/DoMain/board/static/style.css
  src/DoMain/board/templates/customPage.html
  src/DoMain/board/templates/mainbar.html
  src/DoMain/board/templates/test.html
  src/DoMain/board/tests.py
  src/DoMain/board/urls.py
  src/DoMain/board/views.py
  src/DoMain/mainpage/static/js/modal.js
  src/DoMain/mainpage/templates/mainpage.html
  src/DoMain/mainpage/urls.py
  src/DoMain/mainpage/views.py
  src/DoMain/store/migrations/0001_initial.py
  src/DoMain/store/migrations/__init__.py
  src/DoMain/store/models.py
  src/DoMain/widget/static/css/note.css
  src/DoMain/widget/static/dday/dday-element.js
  src/DoMain/widget/static/dday/dday.js
  src/DoMain/widget/static/finance/finance-element.js
  src/DoMain/widget/static/finance/finance.js
  src/DoMain/widget/static/searching/searching-element.js
  src/DoMain/widget/static/searching/searching.js
  src/DoMain/widget/static/stickynote/stickynote-element.js
  src/DoMain/widget/static/stickynote/stickynote.js
  src/DoMain/widget/static/utils/raw-widget.txt
  src/DoMain/widget/templates/stickynote.html
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#52 [FE]- linked back - front
  src/DoMain/account/admin.py
  src/DoMain/store/admin.py
  src/DoMain/store/migrations/0002_comment.py
  src/DoMain/store/models.py
  src/DoMain/store/templates/detailpage.html
  src/DoMain/store/templates/subpage.html
  src/DoMain/store/urls.py
  src/DoMain/store/views.py
Labels: feat

#55 [feat] - Test data insertion request
  src/DoMain/DoMain/urls.py
  src/DoMain/board/views.py
Labels: enhancement, feat

#56 [widget] - timer widget
  src/DoMain/board/static/font/clock.ttf
  src/DoMain/widget/static/timer/timer.js
  src/DoMain/widget/templates/timer.html
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#57 [Rendering] - Till timer widget
  src/DoMain/board/static/css/widget-static-style.css
  src/DoMain/board/static/js/layout-server.js
  src/DoMain/board/templates/test.html
  src/DoMain/board/views.py
  src/DoMain/widget/static/timer/timer-element.js
  src/DoMain/widget/static/timer/timer.js
  src/DoMain/widget/templates/timer.html
Labels: enhancement, feat

#54 [FE]- feat: detailpage reply added
  src/DoMain/account/templates/login.html
  src/DoMain/store/admin.py
  src/DoMain/store/migrations/0003_auto_20210809_0004.py
  src/DoMain/store/models.py
  src/DoMain/store/static/css/detailpage2.css
  src/DoMain/store/static/css/detailwidget.css
  src/DoMain/store/templates/detailpage.html
  src/DoMain/store/urls.py
  src/DoMain/store/views.py
Labels: feat

#60 [sub02] - merge to main
  src/DoMain/account/static/css/login.css
  src/DoMain/account/static/js/join.js
  src/DoMain/account/templates/join.html
  src/DoMain/account/templates/login.html
  src/DoMain/account/views.py
  src/DoMain/mainpage/templates/test.html
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#61 [widget] - merge to main
  src/DoMain/account/views.py
  src/DoMain/board/static/css/widget-static-style.css
  src/DoMain/board/static/font/clock.ttf
  src/DoMain/board/static/image/magnifying-glass.png
  src/DoMain/board/static/js/layout-server.js
  src/DoMain/board/templates/test.html
  src/DoMain/board/urls.py
  src/DoMain/board/views.py
  src/DoMain/widget/static/css/note.css
  src/DoMain/widget/static/dday/dday-element.js
  src/DoMain/widget/static/dday/dday.js
  src/DoMain/widget/static/finance/finance-element.js
  src/DoMain/widget/static/finance/finance.js
  src/DoMain/widget/static/searching/searching-element.js
  src/DoMain/widget/static/searching/searching.js
  src/DoMain/widget/static/stickynote/stickynote-element.js
  src/DoMain/widget/static/stickynote/stickynote.js
  src/DoMain/widget/static/timer/timer-element.js
  src/DoMain/widget/static/timer/timer.js
  src/DoMain/widget/static/utils/raw-widget.txt
  src/DoMain/widget/templates/stickynote.html
  src/DoMain/widget/templates/timer.html
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#62 [FE]- AssetStoreMainPage.html edited
  src/DoMain/store/static/css/Mainpage.css
  src/DoMain/store/static/css/carousel.css
  src/DoMain/store/static/image/customize-animated.gif
  src/DoMain/store/static/image/customize-static.gif
  src/DoMain/store/static/image/store-active.gif
  src/DoMain/store/static/image/store-static.gif
  src/DoMain/store/templates/AssetStoreMainPage.html
Labels: feat

#59 [BE] - Feat: widget, layout download in store
  src/DoMain/store/templates/detailpage.html
  src/DoMain/store/urls.py
  src/DoMain/store/views.py
  src/DoMain/widget/admin.py
Labels: feat

#63 Merge Sub01
  src/DoMain/account/admin.py
  src/DoMain/account/templates/login.html
  src/DoMain/store/admin.py
  src/DoMain/store/migrations/0002_comment.py
  src/DoMain/store/migrations/0003_auto_20210809_0004.py
  src/DoMain/store/models.py
  src/DoMain/store/static/css/Mainpage.css
  src/DoMain/store/static/css/carousel.css
  src/DoMain/store/static/css/detailpage2.css
  src/DoMain/store/static/css/detailwidget.css
  src/DoMain/store/static/css/subpage.css
  src/DoMain/store/static/image/customize-animated.gif
  src/DoMain/store/static/image/customize-static.gif
  src/DoMain/store/static/image/store-active.gif
  src/DoMain/store/static/image/store-static.gif
  src/DoMain/store/templates/AssetStoreMainPage.html
  src/DoMain/store/templates/detailpage.html
  src/DoMain/store/templates/subpage.html
  src/DoMain/store/urls.py
  src/DoMain/store/views.py
  src/DoMain/widget/admin.py
Labels: feat

#67 [Rendering] - merge to main
  src/DoMain/board/static/css/widget-static-style.css
  src/DoMain/board/static/js/layout-server.js
  src/DoMain/board/views.py
  src/DoMain/widget/static/dday/dday-element.js
  src/DoMain/widget/static/dday/dday.js
  src/DoMain/widget/static/finance/finance-element.js
  src/DoMain/widget/static/finance/finance.js
  src/DoMain/widget/static/searching/searching-element.js
  src/DoMain/widget/static/searching/searching.js
  src/DoMain/widget/static/stickynote/stickynote-element.js
  src/DoMain/widget/static/stickynote/stickynote.js
  src/DoMain/widget/static/timer/timer-element.js
  src/DoMain/widget/static/timer/timer.js
  src/DoMain/widget/views.py
Labels: enhancement, feat

#69 feat : add apply_layout func
  src/DoMain/board/templates/test2.html
  src/DoMain/board/urls.py
  src/DoMain/board/views.py
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#70 feat : create update-request.js
  src/DoMain/board/static/js/update-request.js
Labels: enhancement, feat

#74 [FE] - Feat: my page
  src/DoMain/store/static/css/mypage/mypage.css
  src/DoMain/store/static/css/mypage/profile.css
  src/DoMain/store/static/css/mypage/profileNomalize.css
  src/DoMain/store/templates/myPage.html
  src/DoMain/store/views.py
Labels: feat

#80 [FE, BE]- Reply comment function added & style edited
  src/DoMain/DoMain/templates/base.html
  src/DoMain/store/static/css/Mainpage.css
  src/DoMain/store/static/css/carousel.css
  src/DoMain/store/static/css/detailpage.css
  src/DoMain/store/static/css/detailwidget.css
  src/DoMain/store/templates/AssetStoreMainPage.html
  src/DoMain/store/templates/detailpage.html
  src/DoMain/store/urls.py
  src/DoMain/store/views.py
Labels: feat

#96 [Rendering] - append a new widget into an applied layout
  src/DoMain/board/templates/home.html
  src/DoMain/board/views.py
  src/DoMain/store/views.py
  src/DoMain/widget/models.py
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#104 [FE] - Feat : store/main
  src/DoMain/store/templates/AssetStoreMainPage.html
  src/DoMain/store/templates/myPage.html
  src/DoMain/store/views.py
Labels: feat

#107 [Widget] resize stickynote widget content box
  src/DoMain/board/static/css/widget-modal.css
  src/DoMain/board/static/js/widget-contents-data.js
  src/DoMain/board/static/js/widget-contents-modal.js
  src/DoMain/widget/static/stickynote/stickynote.js
Labels: enhancement, feat

#110 refactor: fix reply comment
  src/DoMain/store/templates/detailpage.html
  src/DoMain/store/views.py
Labels: feat

#112 [FE]- Refactor overall store pages
  src/DoMain/DoMain/templates/base.html
  src/DoMain/DoMain/urls.py
  src/DoMain/account/static/css/base.css
  src/DoMain/account/static/css/login.css
  src/DoMain/account/templates/login.html
  src/DoMain/account/urls.py
  src/DoMain/account/views.py
  src/DoMain/store/static/css/commons/navbar.css
  src/DoMain/store/templates/AssetStoreMainPage.html
  src/DoMain/store/templates/detailpage.html
Labels: feat
