Repository LikeLion-CAU-9th/DoMain, pull requests merged in 2021-07, with the labels that each got.

#1 Feat account mail validation
  src/DoMain/DoMain/settings.py
  src/DoMain/DoMain/urls.py
  src/DoMain/account/models.py
  src/DoMain/account/static/css/base.css
  src/DoMain/account/static/css/join.css
  src/DoMain/account/static/css/login.css
  src/DoMain/account/templates/join.html
  src/DoMain/account/templates/login.html
  src/DoMain/account/text.py
  src/DoMain/account/tokens.py
  src/DoMain/account/urls.py
  src/DoMain/account/views.py
Labels: enhancement

#2 doc : update dataflow diagram
  docs/diagram/DataFlow.png
Labels: documentation

#3 [feat] - account/models
  src/DoMain/account/models.py
Labels: enhancement

#4 Hotfix-BE-refactor: settings.py
  .gitignore
  src/DoMain/DoMain/settings.py
Labels: hotfix

#5 refactor: fix module error
  src/DoMain/DoMain/settings.py
  src/DoMain/requirements.txt
Labels: hotfix

#9 [FE] - Finance widget
  docs/diagram/DataFlow.png
  src/DoMain/account/README.md
  src/DoMain/account/models.py
  src/DoMain/widget/finance.py
  src/DoMain/widget/static/finance/finance.js
  src/DoMain/widget/templates/finance.html
  src/DoMain/widget/urls.py
  src/DoMain/widget/views.py
Labels: enhancement, feat

#6 [FE]- Store main page created/edited
  src/DoMain/DoMain/urls.py
  src/DoMain/store/static/css/Mainpage.css
  src/DoMain/store/static/css/carousel.css
  src/DoMain/store/static/image/Desktop - 8.png
  src/DoMain/store/static/image/Desktop - 9 (1).png
  src/DoMain/store/static/image/Desktop - 9.png
  src/DoMain/store/static/image/Group 10.png
  src/DoMain/store/static/image/Group 12.png
  src/DoMain/store/static/image/image 23.png
  src/DoMain/store/static/image/image 24.png
  src/DoMain/store/static/image/weekly-best-image-1.png
  src/DoMain/store/static/image/weekly-best-image.png
  src/DoMain/store/static/image/widget-recommend.png
  src/DoMain/store/static/js/carousel.js
  src/DoMain/store/templates/MainPage.html
  src/DoMain/store/urls.py
  src/DoMain/store/views.py
Labels: feat

#16 [FE] - Feat: subpage in store
  src/DoMain/store/static/css/commons/card.css
  src/DoMain/store/static/css/commons/dropdown.css
  src/DoMain/store/static/css/commons/search.css
  src/DoMain/store/static/css/subPage/cardSubPage.css
  src/DoMain/store/static/css/subPage/tabMenuBar.css
  src/DoMain/store/static/css/subpage.css
  src/DoMain/store/static/css/upperSubPage.css
  src/DoMain/store/static/image/bannerSubPage1.png
  src/DoMain/store/static/image/bannersubPage.png
  src/DoMain/store/static/js/cardDetailEffect.js
  src/DoMain/store/templates/subpage.html
Labels: feat

#17 [FE] - Refactor: connect pages
  src/DoMain/store/static/css/subPage/cardSubPage.css
  src/DoMain/store/static/css/subpage.css
  src/DoMain/store/static/js/cardDetailEffect.js
  src/DoMain/store/templates/MainPage.html
  src/DoMain/store/templates/detailpage.html
  src/DoMain/store/templates/landingPage.html
  src/DoMain/store/templates/subpage.html
  src/DoMain/store/urls.py
  src/DoMain/store/views.py
Labels: fix

#21 [Sub02] - Account features
  docs/diagram/DataFlow.png
  src/DoMain/account/README.md
  src/DoMain/account/models.py
  src/DoMain/account/static/css/join.css
  src/DoMain/account/static/js/join.js
  src/DoMain/account/static/js/jquery.js
  src/DoMain/account/templates/fail.html
  src/DoMain/account/templates/join.html
  src/DoMain/account/templates/login.html
  src/DoMain/account/templates/success.html
  src/DoMain/account/urls.py
  src/DoMain/account/views.py
Labels: enhancement, feat

#14 [widget] : refactor finance.py
  src/DoMain/widget/finance.py
Labels: enhancement
